# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    # makes classes in src/AppBundle available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    AppBundle\:
        resource: '../../src/AppBundle/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../src/AppBundle/{Entity,Repository,Service, Twig, Tests}'

    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services
    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    # add more services, or override services that need manual wiring

    # API
    app.api.lifx.light:
        class: 'AppBundle\Service\Lifx\Light'
        arguments:
            - '@csa_guzzle.client.lifx_api'
            - '@serializer.encoder.json'
            - '%lifx_selector%'

    app.api.gitlab.mezzo:
        class: 'AppBundle\Service\Gitlab\Mezzo'
        arguments:
            - '@csa_guzzle.client.gitlab_api'
            - '@serializer'
            - '%gitlab_project_id%'

    # TWIG
    app.twig.extension.trend:
        class: 'AppBundle\Twig\TrendExtension'
        tags:
            - { name: 'twig.extension' }

    # ADMIN LTE
    app.admin_lte.menu_listener:
        class: 'AppBundle\Event\Listener\AdminLte\MenuItemListListener'
        tags:
            - name: 'kernel.event_listener'
              event: 'theme.sidebar_setup_menu'
              method: 'onSetupMenu'

    # SERVICE
    app.service.history_manager:
        class: 'AppBundle\Service\HistoryManager'
        public: true
        arguments:
            - '%history_path%'
            - '@filesystem'
            - '@serializer'

    app.service.gitlab.ci_manager:
        class: 'AppBundle\Service\Gitlab\CiManager'
        arguments:
            - '@app.api.gitlab.mezzo'

    app.service.team_flow:
        class: 'AppBundle\Service\TeamFlow'
        arguments:
            - '%redmine_project_id%'
            - '%gitlab_project_id%'
            - '@app.api.lifx.light'
            - '@app.service.manager.artifact'
            - '@serializer'
            - '@filesystem'
            - '@app.service.history_manager'
            - '@app.service.gitlab.ci_manager'

    app.service.manager.artifact:
        class: 'AppBundle\Service\ArtifactManager'
        arguments:
            - '%artifact_path%'
            - '@filesystem'
            - '@serializer'
            - '@app.api.gitlab.mezzo'

    app.service.artifact.clover_parser:
        class: 'AppBundle\Service\Artifact\PhpunitCloverParser'
        arguments:
            - '%artifact_path%'

